// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sebbhngqwjskpbxmmlvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlYmJobmdxd2pza3BieG1tbHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNjMwNjEsImV4cCI6MjA1NjgzOTA2MX0.9eqB9uRQXe9_AwCrDT7fcLujdhnkRrtfnK4hpZka_qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);